package com.ming.cnbeta.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ming.cnbeta.db.greendao.NewsItem;
import com.ming.cnbeta.db.greendao.NewsDetail;
import com.ming.cnbeta.db.greendao.CommentItem;

import com.ming.cnbeta.db.greendao.NewsItemDao;
import com.ming.cnbeta.db.greendao.NewsDetailDao;
import com.ming.cnbeta.db.greendao.CommentItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsItemDaoConfig;
    private final DaoConfig newsDetailDaoConfig;
    private final DaoConfig commentItemDaoConfig;

    private final NewsItemDao newsItemDao;
    private final NewsDetailDao newsDetailDao;
    private final CommentItemDao commentItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsItemDaoConfig = daoConfigMap.get(NewsItemDao.class).clone();
        newsItemDaoConfig.initIdentityScope(type);

        newsDetailDaoConfig = daoConfigMap.get(NewsDetailDao.class).clone();
        newsDetailDaoConfig.initIdentityScope(type);

        commentItemDaoConfig = daoConfigMap.get(CommentItemDao.class).clone();
        commentItemDaoConfig.initIdentityScope(type);

        newsItemDao = new NewsItemDao(newsItemDaoConfig, this);
        newsDetailDao = new NewsDetailDao(newsDetailDaoConfig, this);
        commentItemDao = new CommentItemDao(commentItemDaoConfig, this);

        registerDao(NewsItem.class, newsItemDao);
        registerDao(NewsDetail.class, newsDetailDao);
        registerDao(CommentItem.class, commentItemDao);
    }
    
    public void clear() {
        newsItemDaoConfig.getIdentityScope().clear();
        newsDetailDaoConfig.getIdentityScope().clear();
        commentItemDaoConfig.getIdentityScope().clear();
    }

    public NewsItemDao getNewsItemDao() {
        return newsItemDao;
    }

    public NewsDetailDao getNewsDetailDao() {
        return newsDetailDao;
    }

    public CommentItemDao getCommentItemDao() {
        return commentItemDao;
    }

}
