package com.ming.cnbeta.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table tb_NewsDetail.
 */
public class NewsDetail {

    private String sid;
    private String SN;
    private String title;
    private String date;
    private String source;
    private String sourceLink;
    private String intro;
    private Integer topicId;
    private String topicTitle;
    private String topicImage;
    private String content;
    private String author;
    private Integer comment_num;
    private Integer view_num;

    public NewsDetail() {
    }

    public NewsDetail(String sid) {
        this.sid = sid;
    }

    public NewsDetail(String sid, String SN, String title, String date, String source, String sourceLink, String intro, Integer topicId, String topicTitle, String topicImage, String content, String author, Integer comment_num, Integer view_num) {
        this.sid = sid;
        this.SN = SN;
        this.title = title;
        this.date = date;
        this.source = source;
        this.sourceLink = sourceLink;
        this.intro = intro;
        this.topicId = topicId;
        this.topicTitle = topicTitle;
        this.topicImage = topicImage;
        this.content = content;
        this.author = author;
        this.comment_num = comment_num;
        this.view_num = view_num;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    public String getSN() {
        return SN;
    }

    public void setSN(String SN) {
        this.SN = SN;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getSourceLink() {
        return sourceLink;
    }

    public void setSourceLink(String sourceLink) {
        this.sourceLink = sourceLink;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public Integer getTopicId() {
        return topicId;
    }

    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    public String getTopicTitle() {
        return topicTitle;
    }

    public void setTopicTitle(String topicTitle) {
        this.topicTitle = topicTitle;
    }

    public String getTopicImage() {
        return topicImage;
    }

    public void setTopicImage(String topicImage) {
        this.topicImage = topicImage;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Integer getComment_num() {
        return comment_num;
    }

    public void setComment_num(Integer comment_num) {
        this.comment_num = comment_num;
    }

    public Integer getView_num() {
        return view_num;
    }

    public void setView_num(Integer view_num) {
        this.view_num = view_num;
    }

}
